trigger:
  branches:
    include:
      - master
  paths:
    include:
      - /terpoc/terraform/variables.tf
      - /terpoc/terraform/main.tf
 
pool:
  vmImage: "ubuntu-latest"
 
variables:
  - group: Terraform-BuildVariables
  - name: subscription_id
    value: ""
  - name: application_id
    value: ""
  - name: tenant_id
    value: ""
  - name: storage_accounts
    value: "saterpoc"
  - name: blob_storage
    value: container01-terpoc
  - name: state_file
    value: tf-statefile.state
  - name: sa-resource_group
    value: terpocgrp
 
steps:
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: 'Install Terraform'
  - script: terraform version
    displayName: Terraform Version
  - script:  az login --service-principal -u $(application_id) -p $(spn-key) --tenant $(tenant_id)
    displayName: 'Log Into Azure'
  - script: terraform init -backend-config=resource_group_name=$(sa-resource_group) -backend-config="storage_account_name=$(storage_accounts)" -backend-config="container_name=$(blob_storage)" -backend-config="access_key=$(saterpoc-secret)" -backend-config="key=$(state_file)"
    displayName: "Terraform Init"
    workingDirectory: $(System.DefaultWorkingDirectory)/terpoc/terraform
  - script: terraform plan -var="client_id=$(application_id)" -var="client_secret=$(spn-key)" -var="tenant_id=$(tenant_id)" -var="subscription_id=$(subscription_id)" -var="admin_password=$(vm-admin-password)" -out="out.plan"
    displayName: Terraform Plan
    workingDirectory: $(System.DefaultWorkingDirectory)/terpoc/terraform
  - script: terraform apply out.plan
    displayName: 'Terraform Apply'
    workingDirectory: $(System.DefaultWorkingDirectory)/terpoc/terraform
